Repository TeamSodam/sodam-server, pull requests merged in 2022-01, with the labels that each got.

#4 ➕ [ADD] : user폴더 index.js 추가 #3
  .github/workflows/main_deploy.yml
  src/routes/user/index.js
Labels: 🥝 feature

#9 🔨 [FIX] : DB 연동 오류 해결 #5
  package-lock.json
  src/script/spreadsheet.js
Labels: 🛠 fix

#10 Feature/spreadsheet #5
  .gitignore
  package-lock.json
  package.json
  src/db/index.js
  src/db/spreadsheet.js
  src/script/spreadsheet.js
Labels: 🥝 feature

#17 Feature/get bookmarked shop #16
  src/constants/responseMessage.js
  src/db/shop.js
  src/routes/shop/bookmarkGET.js
  src/routes/shop/index.js
  src/routes/shop/shopGET.js
Labels: 🥝 feature

#21 ✨ [FEAT] : [POST] /review/:reviewId/like api 완성 #18
  src/constants/responseMessage.js
  src/db/index.js
  src/db/review.js
  src/routes/index.js
  src/routes/review/index.js
  src/routes/review/reviewLikePOST.js
Labels: 🥝 feature

#24 [FEATURE] [POST] /review/:reviewId/scrap api 완성 #22
  src/db/review.js
  src/routes/review/index.js
  src/routes/review/reviewLikePOST.js
  src/routes/review/reviewScrapPOST.js
Labels: 🥝 feature

#30 ✨ [FEAT] : [GET] /shop/:shopId/review/:reviewId api제작 #25
  src/constants/responseMessage.js
  src/db/review.js
  src/routes/shop/index.js
  src/routes/shop/shopReviewIdGET.js
Labels: 🥝 feature

#45 Feature/sign up, log in 회원가입, 로그인 구현
  package-lock.json
  package.json
  src/constants/responseMessage.js
  src/db/user.js
  src/lib/jwtHandlers.js
  src/middlewares/auth.js
  src/routes/auth/authLoginPOST.js
  src/routes/auth/authSignupPOST.js
  src/routes/auth/index.js
  src/routes/index.js
  src/routes/shop/bookmarkGET.js
Labels: 🥝 feature

#28 [FEATURE] [GET] /shop/recommend?type api 완성 #23
  src/constants/responseMessage.js
  src/db/shop.js
  src/routes/shop/index.js
  src/routes/shop/shopRecommendGET.js
  src/sodam-server-authentication.json
Labels: 🥝 feature

#32 [FEATURE] [GET] /shop/category?type api 완성 #29
  src/constants/responseMessage.js
  src/db/shop.js
  src/routes/shop/index.js
  src/routes/shop/shopCategoryGET.js
Labels: 🥝 feature

#35 [FEATURE] [GET] /review/recent #33
  src/constants/responseMessage.js
  src/db/review.js
  src/routes/review/index.js
  src/routes/review/reviewRecentGET.js
Labels: 🥝 feature

#37 [FEATURE] [GET] /shop/search?keyword #36
  src/constants/responseMessage.js
  src/db/shop.js
  src/routes/shop/index.js
  src/routes/shop/shopSearchGET.js
Labels: 🥝 feature

#31 Feature/recommend shop by subway 20
  src/constants/responseMessage.js
  src/db/shop.js
  src/routes/shop/index.js
  src/routes/shop/shopShopIdLocationGET.js
Labels: 🥝 feature

#51 ➕ [ADD] : 마이리뷰에 checkuser 미들웨어 붙이기 #50
  src/db/review.js
  src/routes/my/index.js
  src/routes/my/myReviewGET.js
  src/routes/my/myScrapGET.js
Labels: 🛠 fix

#53 Feature/slack webhook #49
  package-lock.json
  package.json
  src/middlewares/slackAPI.js
  src/routes/auth/authLoginPOST.js
  src/routes/auth/authSignupPOST.js
  src/routes/my/myReviewGET.js
  src/routes/my/myScrapGET.js
  src/routes/review/reviewLikePOST.js
  src/routes/review/reviewRecentGET.js
  src/routes/review/reviewScrapPOST.js
  src/routes/review/reviewShopIdSortPageGET.js
  src/routes/shop/bookmarkGET.js
  src/routes/shop/bookmarkPOST.js
  src/routes/shop/shopCategoryGET.js
  src/routes/shop/shopGET.js
  src/routes/shop/shopRecommendGET.js
  src/routes/shop/shopReviewIdGET.js
  src/routes/shop/shopSearchGET.js
  src/routes/shop/shopShopIdGET.js
  src/routes/shop/shopShopIdLocationGET.js
  src/routes/user/userGET.js
Labels: 🥝 feature

#55 ✨ [FEAT] : 유저, 리뷰 관련 더미데이터 스크립트 작성 #44
  package-lock.json
  package.json
  src/db/spreadsheet.js
  src/script/inserShop.js
  src/script/insertReviewData.js
  src/script/insertReviewImage.js
  src/script/insertReviewItem.js
  src/script/insertReviewTag.js
  src/script/insertTag.js
  src/script/insertUser.js
Labels: 🥝 feature

#59 🔨 [FIX] : 작성자 썸네일 이미지 스트링 배열로 변경 #56
  src/routes/review/reviewShopIdSortPageGET.js
Labels: 🛠 fix

#60 🔨 [FIX] : 유저 썸네일 이미지 배열로 고치기 #56
  src/routes/review/reviewRecentGET.js
Labels: 🛠 fix

#63 [BUG] shop review #61
  src/routes/review/reviewShopIdSortPageGET.js
Labels: 🚨 bug, 🛠 fix

#65 [FIX] 내가 작성한 리뷰 response 수정
  src/constants/responseMessage.js
  src/routes/my/myReviewGET.js
Labels: 🛠 fix

#66 [FIX] 오류 사항 수정
  src/constants/responseMessage.js
  src/db/review.js
  src/routes/my/myReviewGET.js
  src/routes/my/myScrapGET.js
  src/routes/review/reviewShopIdSortPageGET.js
Labels: 🛠 fix

#69 🔨 [FIX] : 리뷰 작성 슬랙 웹훅 연결 및 오류 해결 #68
  src/routes/review/reviewPOST.js
Labels: 🚨 bug

#71 🔨 [FIX] : 리뷰 상세 response 맞추기 #70
  src/db/review.js
  src/routes/shop/shopReviewIdGET.js
Labels: 🚨 bug

#76 🔨 [FIX] : 소품샵 상세페이지 좋아요, 스크랩, date 오류 고침 #74 #75
  src/routes/shop/index.js
  src/routes/shop/shopReviewIdGET.js
Labels: 🚨 bug, 🛠 fix

#72 [MERGE] 수정 사항 반영
  src/db/review.js
  src/routes/my/myReviewGET.js
  src/routes/review/reviewPOST.js
  src/routes/shop/index.js
  src/routes/shop/shopReviewIdGET.js
Labels: 🛠 fix

#77 🔨 [FIX] : 좋아요, 스크랩 고침 #75
  src/routes/shop/shopReviewIdGET.js
Labels: 🚨 bug, 🛠 fix

#78 [MERGE] 최신 리뷰, 좋아요, 스크랩 수정 사항 반영
  src/db/review.js
  src/routes/shop/shopReviewIdGET.js
Labels: 🚨 bug, 🛠 fix

#81 🔨 [FIX] : 리뷰 작성 잘못된 값 request 가드 #80
  src/constants/responseMessage.js
  src/routes/review/reviewPOST.js
Labels: 🚨 bug, 🛠 fix

#79 [MERGE] 수정사항 반영 및 리드미 수정
  README.md
  src/constants/responseMessage.js
  src/db/review.js
  src/routes/review/reviewPOST.js
  src/script/insertShop.js
Labels: 🚨 bug, 🛠 fix

#83 🔨 [FIX] : 리뷰 상세 response로 항상 같은 item 나오는 버그 수정 #82
  src/routes/shop/shopReviewIdGET.js
Labels: 🚨 bug, 🛠 fix

#84 [MERGE] 리뷰 상세 모두 같은 아이템이 반환되는 버그 수정
  src/routes/shop/shopReviewIdGET.js
Labels: 🚨 bug, 🛠 fix

#85 [fix] 리뷰 최신순으로 뜨게 변경
  src/db/review.js
Labels: 🔥 hotfix
