Repository TeamSodam/sodam-server, pull requests merged in 2022-06, with the labels that each got.

#164 [FEATURE] 리프레쉬토큰 기능 구현 #126
  package.json
  src/app.js
  src/constants/responseMessage.js
  src/db/user.js
  src/lib/jwtHandlers.js
  src/lib/redis.js
  src/middlewares/auth.js
  src/routes/auth/authLoginPOST.js
  src/routes/auth/index.js
  src/routes/auth/refreshPOST.js
  src/routes/auth/signup/signupPOST.js
Labels: 🥝 feature, 🛠 fix

#166 Feat/admin get 어드민용 인가체계 구축
  src/db/adminUser.js
  src/db/index.js
  src/lib/jwtHandlers.js
  src/middlewares/adminAuth.js
  src/routes/admin/adminLoginPost.js
  src/routes/admin/allReviewGET.js
  src/routes/admin/allShopGET.js
  src/routes/admin/index.js
  src/routes/admin/shopDataGET.js
Labels: 🥝 feature

#168 [fix] 로그인 api response에 닉네임 추가 #167
  src/routes/auth/authLoginPOST.js
Labels: 🛠 fix

#170 [Fix] 회원가입 테마 저장 수정 (fix/post-signup) #169
  src/constants/responseMessage.js
  src/db/user.js
  src/routes/auth/signup/signupPOST.js
Labels: 🚨 bug, 🛠 fix

#176 [CHORE] : S3 버킷 이름 세팅 변경 #171
  src/middlewares/uploadImage.js
Labels: 🦊 chore

#177 ✅ [CHORE] : 소품샵 이미지 DB에 넣기 #174
  src/db/spreadsheet.js
  src/dbscript/insertShopImage.js
Labels: 🦊 chore

#178 rds, s3 세팅 및 소품샵 이미지 데이터 저장
  src/db/spreadsheet.js
  src/dbscript/insertShopImage.js
  src/middlewares/uploadImage.js
Labels: 🦊 chore

#187 🚑️ [HOTFIX] : cors origin multiple url 작동 코드
  src/app.js
Labels: 🔥 hotfix

#189 [FIX] 회원가입 안 되는 오류 수정 fix/signup #188
  src/db/user.js
Labels: 🚨 bug, 🛠 fix

#190 [fix] 회원가입 오류 수정
  src/db/user.js
Labels: 🚨 bug, 🛠 fix

#193 🔨 [FIX] : 소품샵 상세, 리뷰 상세 리뷰 정렬 오류 수정 #192
  src/db/review.js
Labels: 🚨 bug, 🛠 fix
